### ISSUE TITLE
Create Front End Project for Practice App

### ISSUE THREAD

**Issue by bakikucukcakiroglu** [bounswe/bounswe2023group8#118]
This issue involves the task for creating and initializing the front end project of the Practice App using JavaScript's React framework. ( React has been decided as the technology we'll use on the front-end by the team. )

- Install npm and node on the system. 
- Install necessary packages to create a React app using npm. 
- Create a React project named "client". 
- Design and code the first page of the Practice App. 
- Create "master" and "dev" branches on it. 
- Publish this project on remote repository.

**Comment by baki-kucukcakiroglu** [comment]
Done. 

To run client project, clone the code and execute the following commands from the terminal in the client directory:

- npm install

- npm run start

You will get the following page on your local machine. 

<img width="1792" alt="Screenshot 2023-04-30 at 13 48 00" src="https://user-images.githubusercontent.com/113987895/235349045-db374d5a-c25d-469a-b7d9-1383a69dcb42.png">


All the instructions to run project will be added to readme file soon.

**Comment by bakikucukcakiroglu** [comment]
Done.

To run client project, do the followings:
- check if node and npm is installed on your system ( node --version , npm --version)
- if not installed:
    - install the latest version of node to your system (for mac you may use brew)
    - install the latest version of npm (node package manager) to your system(in most scenerios it will be served with node, so check after installing node)
- using terminal clone the repo(git clone URL_OF_REPO) to a directory you want and change directory to "client" using cd command and run the following commands:
    - npm install
    - npm run start

You will get the following page on your local machine.

![](https://user-images.githubusercontent.com/113987895/235349045-db374d5a-c25d-469a-b7d9-1383a69dcb42.png)

All the instructions to run project will be added to readme file soon.

**Comment by begumyivli** [comment]
thank you very useful
