### ISSUE TITLE
Update README.md

### ISSUE THREAD

**Issue by EgemenKaplan** [bounswe/bounswe2023group8#12]
We need to update our landing page with our project description and then keep it updated with appropriate results of our weekly work, such as a link to our requirements, team members.

**Comment by FurkanOzcelik** [comment]
Added a title
Added two sections 'What Are We Working On' and 'Get To Know Us'
Added project description, team informations.
Waiting to get a group photo and add it next to 'Get To Know Us'

**Comment by FurkanOzcelik** [comment]
Group photo added.
