### ISSUE TITLE
Wiki Home Page Main Issue

### ISSUE THREAD

**Issue by bahadirgezer** [bounswe/bounswe2023group8#13]
Update home page with details about our project.

**Comment by bahadirgezer** [comment]
Updated the wiki home page and added a "what is our project about?" section. Commit [link](https://github.com/bounswe/bounswe2023group8/wiki/Home/3b2952c71ea2427dd96a67dece60e64dec28c373).

**Comment by EgemenKaplan** [comment]
I think this might be a duplicate of the issue I created earlier. We cannot delete issues I think so I will label this one as duplicate

**Comment by EgemenKaplan** [comment]
I realized that I misunderstood the difference. You are talking about wiki home page, which is different than Readme.md. My bad.
