### ISSUE TITLE
New feature for Practice App: Wiki Data APIs - Frontend

### ISSUE THREAD

**Issue by baki-kucukcakiroglu** [bounswe/bounswe2023group8#131]
Front end of APIs using Wiki Data external APIs should be implemented.

- A well-looking user interface should be implemented to make user use APIs easily.

**Comment by bakikucukcakiroglu** [comment]
There was a inconsistency between feature branch numbers and the descriptions of the issue. I fixed it by swapping the issues #131 and #148.
