### ISSUE TITLE
Creating template for meeting notes

### ISSUE THREAD

**Issue by begumyivli** [bounswe/bounswe2023group8#16]
Template for every meeting notes

**Comment by sudek0** [comment]
good work! very useful

**Comment by EgemenKaplan** [comment]
Maybe we could add a new "Resources" section that includes links to research or documentation that is related to that day's topics. Its not possible to find resources during meetings consistently, so this section would be just optional to help kick-start the work ahead.

**Comment by begumyivli** [comment]
> good work! very useful

thank you sis

**Comment by begumyivli** [comment]
> Maybe we could add a new "Resources" section that includes links to research or documentation that is related to that day's topics. Its not possible to find resources during meetings consistently, so this section would be just optional to help kick-start the work ahead.
thank you for your good idea, i will add that part

**Comment by begumyivli** [comment]
added new things according to feedbacks and now done
