### ISSUE TITLE
Decide on subteams within the group

### ISSUE THREAD

**Issue by EgemenKaplan** [bounswe/bounswe2023group8#189]
Each member will choose to belong to at least one group mentioned below:
- Front-end/ Web Team
- Back-end Team
- Mobile Team

**Comment by baki-kucukcakiroglu** [comment]
**Web Frontend Team** (5 members)

- @ozturkMirac 
- @EgemenKaplan 
- @sudek0 
- @alabeybahri 
- @orkunkilic 

**Mobile Team** (4 members)

- @MericKeskin 
- @FurkanOzcelik 
- @begumyivli 
- @celikomerfaruk 

**Backend Team** (3 members)
- @bakikucukcakiroglu 
- @bahadirgezer 
- @enesYildiz69 


These roles are assigned to draw a team structure but some members can change their teams for practical purposes.

**Comment by bakikucukcakiroglu** [comment]
We thought that the responsibility of backend team is lighter than other teams so @enesYildiz69  voluntarily transferred to mobile team.  

[For latest version of sub-teams.](https://github.com/bounswe/bounswe2023group8/wiki)

> **Web Frontend Team** (5 members)
> 
> * @ozturkMirac
> * @EgemenKaplan
> * @sudek0
> * @alabeybahri
> * @orkunkilic
> 
> **Mobile Team** (4 members)
> 
> * @MericKeskin
> * @FurkanOzcelik
> * @begumyivli
> * @celikomerfaruk
> 
> **Backend Team** (3 members)
> 
> * @bakikucukcakiroglu
> * @bahadirgezer
> * @enesYildiz69
> 
> These roles are assigned to draw a team structure but some members can change their teams for practical purposes.
