### ISSUE TITLE
Reorganize Wiki and Add First Week Report

### ISSUE THREAD

**Issue by EgemenKaplan** [bounswe/bounswe2023group8#190]
- Archive old reports and meeting notes from CMPE352 under an auto-closed section in the sidebar
- Keep the files regarding the project structure, diagrams, requirements, communication plan etc.

**Comment by bahadirgezer** [comment]
created [first week lab report](https://github.com/bounswe/bounswe2023group8/wiki/1st-Week-Lab-), added it to the sidebar 

reorganized the sidebar to suit both 352 and 451

**Comment by bahadirgezer** [comment]
added [sidebar changes](https://github.com/bounswe/bounswe2023group8/wiki/_Sidebar/9cf0f38f7fa87c6d91bca9bb42d794cc163737fd)
