### ISSUE TITLE
Revising Use Case Diagrams

### ISSUE THREAD

**Issue by sudek0** [bounswe/bounswe2023group8#193]
- [Use Case Diagrams](https://github.com/bounswe/bounswe2023group8/wiki/Use-Case-Diagram) should be revised.

 Any deficiency should be fixed.

**Comment by MericKeskin** [comment]
Use cases are revised according to requirements updates. Fixed deficiencies.

**Comment by MericKeskin** [comment]
According to the changes to requirements, use cases shall be updated

**Comment by MericKeskin** [comment]
Uses cases are [updated](https://github.com/bounswe/bounswe2023group8/wiki/Use-Case-Diagram)
