### ISSUE TITLE
Revising Class Diagrams

### ISSUE THREAD

**Issue by sudek0** [bounswe/bounswe2023group8#195]
- [Class Diagrams](https://github.com/bounswe/bounswe2023group8/wiki/Class-Diagrams) should be revised.

Any deficiency should be fixed.

**Comment by bahadirgezer** [comment]
Created the base class diagrams optimized for the backend. This new diagram holds the core classes to start of the backend project.

**Comment by bahadirgezer** [comment]
Figma [link](https://www.figma.com/file/xRDJrFl2QWtz4lgKIpNHH8/Class-Diagrams-(Backend)?type=whiteboard&node-id=0%3A1&t=zlfaSwG4ADyc4uNW-1) for the refactored class diagrams.

**Comment by bahadirgezer** [comment]
Added the refactored class diagrams to wiki page, commit [link](https://github.com/bounswe/bounswe2023group8/wiki/Refactored-Class-Diagram/3160d6501332e3c534e55d91582fadd850248ed5).

Added the wiki page to the sidebar, commit [link](https://github.com/bounswe/bounswe2023group8/wiki/_Sidebar/1e7be8e25103f2699248d2452960d056f8da8d52).
