### ISSUE TITLE
Revising Sequence Diagrams

### ISSUE THREAD

**Issue by sudek0** [bounswe/bounswe2023group8#196]
- [Sequence Diagrams](https://github.com/bounswe/bounswe2023group8/wiki/Sequence-Diagram) should be revised.

Any deficiency should be fixed.

**Comment by begumyivli** [comment]
added labels and controlled in general

**Comment by EgemenKaplan** [comment]
Merged all search related diagrams into one general search diagram in accordance with our class diagram

**Comment by EgemenKaplan** [comment]
- Removed social media related parts from the sequence diagrams
