### ISSUE TITLE
Deciding on Technologies for Backend

### ISSUE THREAD

**Issue by MericKeskin** [bounswe/bounswe2023group8#202]
The technologies that will be used by Backend team will be argued. The outcomes should be inspected by other teams for the coherence.

- [x]  Argued for the technologies
- [ ] #205
- [ ]  Inspections are completed

**Comment by bahadirgezer** [comment]
Spring would be a good choice mainly because of our **affinity** with it. It's a flexible framework with powerful functionality. Also it's quick interoperability with different databases, quick configuration, easy layering, and easy serialization-deserialization configurations.
