### ISSUE TITLE
Deciding on the Technologies for Frontend

### ISSUE THREAD

**Issue by MericKeskin** [bounswe/bounswe2023group8#204]
The technologies that will be used by Frontend team will be argued. The outcomes should be inspected by other teams for the coherence.

- [ ]  Argued for the technologies
- [ ]  Technologies are decided and listed to wiki
- [ ]  Inspections are completed

**Comment by sudek0** [comment]
Frontend base technologies:
- ReactJS framework on Javascript for development
- React Bootstrap for style

**Comment by sudek0** [comment]
[Technologies to be Used](https://github.com/bounswe/bounswe2023group8/wiki/Technologies-to-be-Used)
