### ISSUE TITLE
Deciding on the Branch Policy

### ISSUE THREAD

**Issue by MericKeskin** [bounswe/bounswe2023group8#213]
As we initialize our projects, we need to reconsider our branch policy

**Comment by MericKeskin** [comment]
Decided to create different branches for different parts of our projects. For starting every part will have a master and develop branch of their own.

**Comment by MericKeskin** [comment]
Argued on the branch policy and agreed on a cohere branch system that will separate both practice app and web aggregator, and units which are backend, frontend and mobile.

**Comment by bakikucukcakiroglu** [comment]
I think we agreed on the policy, this issue can be closed!

**Comment by MericKeskin** [comment]
branch policy wiki page is completed
