### ISSUE TITLE
Backend - Add User Service and Authentication 

### ISSUE THREAD

**Issue by bahadirgezer** [bounswe/bounswe2023group8#226]
Add the EnigmaUserService with: 
- [x]  login #256 
- [x]  register #257 
functionality

**Comment by bahadirgezer** [comment]
* forgot password

**Comment by bakikucukcakiroglu** [comment]
Updated issue as login and register since forgot-password doesn't belong to authentication.

**Comment by bakikucukcakiroglu** [comment]
Both login and register mechanisms are implemented. The comments related to work done for this issue can be seen in sub-issues #256 and #257.
