### ISSUE TITLE
Backend - Develop a Working Version of the Interest Area Model

### ISSUE THREAD

**Issue by bahadirgezer** [bounswe/bounswe2023group8#230]

**Comment by bakikucukcakiroglu** [comment]
Create Entity and Repository classes according to class:

<img width="356" alt="Screenshot 2023-10-24 at 15 53 13" src="https://github.com/bounswe/bounswe2023group8/assets/61244299/8c045031-66ff-4a00-a0a6-be8bfa2adef0">

**Comment by bakikucukcakiroglu** [comment]
https://github.com/bounswe/bounswe2023group8/commit/13c3c0547ebd613971eab46a6b52efcc42ddbd77
