### ISSUE TITLE
Backend - Develop the First Version of the Post Model

### ISSUE THREAD

**Issue by bahadirgezer** [bounswe/bounswe2023group8#231]

**Comment by bakikucukcakiroglu** [comment]
Create Entity and Repository classes according to class diagram:
 
<img width="352" alt="Screenshot 2023-10-24 at 15 48 30" src="https://github.com/bounswe/bounswe2023group8/assets/61244299/618cb154-254b-4996-9c05-47a7374eeca7">

**Comment by bakikucukcakiroglu** [comment]
[#2145d20e6b1d55e30792846b8a5ab8b9600e5311](https://github.com/bounswe/bounswe2023group8/commit/2145d20e6b1d55e30792846b8a5ab8b9600e5311)
