### ISSUE TITLE
Setup GCS MySQL Server Connection for Development

### ISSUE THREAD

**Issue by bahadirgezer** [bounswe/bounswe2023group8#239]

**Comment by bakikucukcakiroglu** [comment]
We decided to use Amazon RDS instead. We will use AWS EC2 so a database which is also a product of AWS will be more convenient. Necessary arrangements are done to allow using AWS RDS. They include changing security settings of EC2 and RDS instances in a way that thay allow reuqests coming from each other. 

#285
