### ISSUE TITLE
Backend: Email Verification for User Registration

### ISSUE THREAD

**Issue by baki-kucukcakiroglu** [bounswe/bounswe2023group8#280]
As part of our user registration process, we aim to enhance security and user experience by implementing an email verification service. This will ensure that the users are using legitimate email addresses and also provide an added layer of protection against bots and unauthorized registrations.

Goals:

- Integration with Email Service: Integrate the backend with an email service (e.g., SendGrid, Mailgun, or SMTP configurations) to facilitate the sending of verification emails.

- Generating Verification Token: When a new user registers, generate a unique verification token for the user.

- Storing the Token: Store the generated token with a timestamp in the database. This token will be used later for validation purposes.

- Sending Verification Email: Send an email to the user with a link to verify their account. The link should contain the generated token.

- Handling Verification: Once the user clicks on the link, validate the token. If the token is valid, mark the user's email as verified in our system.

- Expiration of Token: Ensure that the verification token expires after a set duration (e.g., 24 hours) for security purposes.

- Error Handling: Proper error messages should be shown for invalid or expired tokens.

**Comment by bakikucukcakiroglu** [comment]
- [ ]  Integrate with chosen email service and configure necessary credentials.
- [ ]  Create a service to generate, store, and validate verification tokens.
- [ ]  Implement the email sending mechanism with a constructed verification link.
- [ ]  Handle the endpoint where users will be directed after clicking on the verification link.
- [ ]  Update the user's status in the database upon successful verification.
- [ ]  Implement error handling for token-related issues.

**Comment by bakikucukcakiroglu** [comment]
Notes:

- AWS SES is used as email service. 
- bunchup.com.tr` domain is configured to be domain of verification mails. (no-reply.bunchup.com.tr)

These required configuring DNS setting of domain name via hosting provider platform.

**Comment by bakikucukcakiroglu** [comment]
#285
