### ISSUE TITLE
Backend - Implementation of /auth/reset-password Endpoint for Password Renewal

### ISSUE THREAD

**Issue by baki-kucukcakiroglu** [bounswe/bounswe2023group8#288]
We need to implement the /auth/reset-password endpoint to allow users to renew their passwords using a token that's sent to their email. This is a follow-up action when a user sends a request to /auth/forgot-password and receives a password reset email.

Request Parameters:

- token: The unique token sent to the user's email to validate their reset password request.
- new_password: The new password the user wants to set.
- confirm_password: Confirmation of the new password to ensure the user has entered it correctly.

**Comment by bakikucukcakiroglu** [comment]
Done.

**Comment by bakikucukcakiroglu** [comment]
#285
