### ISSUE TITLE
Organize the Requirements Elicitation Doc for better structure and navigation.

### ISSUE THREAD

**Issue by EgemenKaplan** [bounswe/bounswe2023group8#34]
- [x] Organize the Document that was created in the meeting by the team (Egemen Kaplan)
- [x] Place it in Wiki in an appropriate way (Bahadır Gezer)

[Requirements Elicitation first draft](https://docs.google.com/document/d/1j7U9XVReVF4p3UNY0aV1eA9C5YjGPcoHKh8gsf3zaK0/edit?usp=sharing)

**Comment by EgemenKaplan** [comment]
I finished organizing the document but of course it wont be fully structured until we precisely know how Requirements list is supposed to be made. Its at least more readable now 😆

**Comment by bahadirgezer** [comment]
Added the requirements draft page. Commit [link](https://github.com/bounswe/bounswe2023group8/wiki/Requirements-Draft/5aceb2ca68e041f7a081e428f3865a48066e8f4f)

**Comment by bahadirgezer** [comment]
Added the new page to the wiki sidebar. Commit [link](https://github.com/bounswe/bounswe2023group8/wiki/_Sidebar/da1c362e6ac1e06515fe97a0417ba6d34b94e5f0)

**Comment by bahadirgezer** [comment]
Task done.
