### ISSUE TITLE
Edit Mockups - Add Geolocation to Mockups

### ISSUE THREAD

**Issue by EgemenKaplan** [bounswe/bounswe2023group8#350]
Geolocation UI should be added to post creation and post view mockups

**Comment by sudek0** [comment]
Completed.

When you click the blue button on the right, pop up shows up.
<img width="1070" alt="Spot View" src="https://github.com/bounswe/bounswe2023group8/assets/110811440/037b248b-3c87-4803-beae-62a7f609f214">

Users can write the location or pick from the map.
<img width="965" alt="Create a Spot" src="https://github.com/bounswe/bounswe2023group8/assets/110811440/9176cec2-7e7e-431e-83aa-a8f7207de350">

Location Pop-up
<img width="626" alt="Map Pop-up" src="https://github.com/bounswe/bounswe2023group8/assets/110811440/9287bdf3-2472-4a2f-accb-d4d2746fa24d">
