### ISSUE TITLE
Improve non-functional requirements

### ISSUE THREAD

**Issue by orkunkilic** [bounswe/bounswe2023group8#36]
Improve non-functional requirements and research to detail more.

**Comment by MericKeskin** [comment]
Added formalized non-functional requirements to requirements page.

**Comment by orkunkilic** [comment]
Requirements wiki looks good to me. Closing this issue? @MericKeskin @enesYildiz69

**Comment by MericKeskin** [comment]
> Requirements wiki looks good to me. Closing this issue? @MericKeskin @enesYildiz69

Let's wait for the weekly meeting to talk over the issue and then close it if it is ok. @enesYildiz69 @orkunkilic

**Comment by MericKeskin** [comment]
Issue completed, but not closed. Closing now.
