### ISSUE TITLE
Creating Mockups for Mobile and Web

### ISSUE THREAD

**Issue by begumyivli** [bounswe/bounswe2023group8#37]
We need to research about mock ups and create for mobile and web applications separately

**Comment by bahadirgezer** [comment]
Creating web mock-ups for:

- New Post 
- Created Post (general post page)
- Interest Area
- New Interest Area 
- Notification (pop-up)
- Message (pop-up)
- Settings

**Comment by bahadirgezer** [comment]
Finished we mockups

**Comment by bahadirgezer** [comment]
All mockups added to wiki. [Wiki addition work](https://github.com/bounswe/bounswe2023group8/issues/43)

**Comment by begumyivli** [comment]
finished web mockups, you can see the figma link on wiki page, got feedback from alper hoca
