### ISSUE TITLE
Mobile - Interest Areas CRUD Endpoints Integration

### ISSUE THREAD

**Issue by MericKeskin** [bounswe/bounswe2023group8#379]
Posts CRUD Endpoints should be integrated to mobile project.

**Comment by celikomerfaruk** [comment]
Update: 
Create Interest Area Endpoint, Search Wikitag Endpoint, Get Interest Area Endpoints Integrated
UI Modifications done accordingly. ie. Search results and selected entities ui created

Delete and update endpoints waiting for edit ia page.

**Comment by celikomerfaruk** [comment]
Delete and Update Endpoints integrated.
Edit Interest Area Page Updated.
Implemented widgets for showing dialog, selecting access level, searching tags and selecting tags.
Provided navigations between ia routes

**Comment by celikomerfaruk** [comment]
Forgot to close the issue. Closing now.
