### ISSUE TITLE
Web - Interest Area Visitor Page

### ISSUE THREAD

**Issue by alabeybahri** [bounswe/bounswe2023group8#382]
Interest Area page for Visitors should be implemented.

**Comment by ozturkMirac** [comment]
Done:
- Developed the visitor page for the interest area now named "bunch."
- Posts are now listed for each bunch.
- Displayed relevant bunch tags and related bunches.
- Utilized existing components and Bootstrap where possible.
- Faced specific requirements that led to the creation of new components.
- Ongoing effort to reconcile and optimize the code.
