### ISSUE TITLE
Assignee limit on issues

### ISSUE THREAD

**Issue by EgemenKaplan** [bounswe/bounswe2023group8#5]
As I was exploring issues and thinking about how we can make better use of them, I noticed that we cannot assign more than 10 people for an issue. Our team consists of 12 people and we might have some tasks that require everyone's attention. Does anyone know whether we can create some sort of "role" for team members so that we can, for example, assign the members of that particular role for an issue?

**Comment by orkunkilic** [comment]
I think it is better to keep issues modular. If an issue requires attention of more than 10 people, I think it should not be one single issue. For example research page requires everyone's attention, but everyone should keep track of its own issues like Orkun's Research page etc.

**Comment by bakikucukcakiroglu** [comment]
Idea: We create issues with a [task list](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/about-task-lists) when the task requires a collaborative work. Thanks to the granularity that the task list type issues provide us, we may able to assign the sub-tasks to each group member. See our [new issue](https://github.com/bounswe/bounswe2023group8/issues/11).
