### ISSUE TITLE
Mock-up revision

### ISSUE THREAD

**Issue by MericKeskin** [bounswe/bounswe2023group8#51]
We got feedback to our mock-ups and should upgrade them on that manner.

**Comment by MericKeskin** [comment]
Created Asset and Mobile page. Assets can be used for coherence of the mock-ups.

**Comment by sudek0** [comment]
Created search and home web and mobile pages.

**Comment by bakikucukcakiroglu** [comment]
Things that is completed by me:

- Revised mobile mock-ups ( moved sidebar nav to the bottom from the side of the screen)
- Added detailing ( border radius, content enrichment , layout fixes)
- Complete revision of Interest Area and Explore pages.

**Comment by MericKeskin** [comment]
- Updated Assets with new icons, colors and other general components.
 - Rearranged Web page of Figma.
 - Reorganized grouping of the Web page frames.
 - Upgraded some of the Web page designs. 
 - Changed unnecessary components to frames and deleted unused attributes to avoid confusion.
 - Made all Web page organizations coherent.

**Comment by FurkanOzcelik** [comment]
- Added Downvote/Upvote Icons to Assets
- Created 'Edit Post' page on Web side
- Created 'Create Post' page on Web side
- Created 'Post' page on Web side
- Created 'Post(For Guests)' page on Web side
- Created 'Edit Post' page on Mobile side
- Created 'Create Post' page on Mobile side
- Created 'Post' page on Mobile side
- Created 'Post(For Guests)' page on Mobile side
- Created 'Post Section' to group all Post related pages

**Comment by FurkanOzcelik** [comment]
- Add editing page for Interest Area

**Comment by begumyivli** [comment]
Work done by me:
Web:

- Created Settings Page for registered users.

- Created Settings Page for visitors.

- Modified View Interest Area Page for registered users.

Mobile:

- Created Settings Page for visitors.

- Created Settings Page for registered users.

**Comment by MericKeskin** [comment]
- Reorganized web mock-ups.
- Web mock-ups are completed and ready for implementing to milestone report.
- New colors, images and icons are added to Assets.
- Pop-up views are added to Assets.

**Comment by MericKeskin** [comment]
- Added check icon to Assets.
- Added navigation bar and tab bar templates to Assets for mobile mock-ups.
- Updated sign up, followers and following pop-ups.
- Added followers and following pop-ups to Assets for mobile mock-ups.
- Updated web mock-ups according to the updates to previous assets.
- Updated and reorganized all mobile mock-ups.
- Added profile section and related pages to mobile mock-ups.

**Comment by MericKeskin** [comment]
Mock-ups are all set for implementing to both wiki and milestone report. Setting the issue type label to review.

**Comment by bakikucukcakiroglu** [comment]
- Borders are added to mockups to prevent them to interfere with white background of the web-pages. 

- Mockups are uploaded to Wiki.
