### ISSUE TITLE
Web - Compliance to Mockups -  Update/Create Bunch Page

### ISSUE THREAD

**Issue by EgemenKaplan** [bounswe/bounswe2023group8#532]
Modify the Update and Create Bunch Pages according to the [new mockup designs](https://www.figma.com/file/4cbCQzzqZlZw2WI0fn5QZX/Mockups?type=design&node-id=811%3A2&mode=design&t=bNpJvPIqCraXYGjQ-1)

**Comment by alabeybahri** [comment]
This [PR](https://github.com/bounswe/bounswe2023group8/pull/567) is changing the design.
