### ISSUE TITLE
Web - Compliance to Mockups - Profile Page

### ISSUE THREAD

**Issue by FurkanOzcelik** [bounswe/bounswe2023group8#536]
Modify the Profile  Page according to the [new mockup designs](https://www.figma.com/file/4cbCQzzqZlZw2WI0fn5QZX/Mockups?type=design&node-id=811%3A2&mode=design&t=bNpJvPIqCraXYGjQ-1)

**Comment by sudek0** [comment]
completed.
[#565](https://github.com/bounswe/bounswe2023group8/pull/565)
