### ISSUE TITLE
Web - Compliance to Mockups -  Small Spot Card Preview

### ISSUE THREAD

**Issue by FurkanOzcelik** [bounswe/bounswe2023group8#540]
Modify the Small Spot Card Preview according to the [new mockup designs](https://www.figma.com/file/4cbCQzzqZlZw2WI0fn5QZX/Mockups?type=design&node-id=811%3A2&mode=design&t=bNpJvPIqCraXYGjQ-1)

**Comment by EgemenKaplan** [comment]
Solved in #554 . Post Preview cards now comply with new mockups
