### ISSUE TITLE
Project - Unit Tests and Reports

### ISSUE THREAD

**Issue by bahadirgezer** [bounswe/bounswe2023group8#628]
Unit tests reports 
* The unit tests must be in the source code and implemented by the person who implemented the relevent code

**Comment by bakikucukcakiroglu** [comment]
Not completed! 

@bahadirgezer was responsible for writing unit test for at least some APIs. I'm added to this issue since I stated that I may help him but he stated that he has not the capability of writing unit tests for our APIs.
