### ISSUE TITLE
Project - API Endpoints

### ISSUE THREAD

**Issue by bahadirgezer** [bounswe/bounswe2023group8#629]
**API Endpoints**

* The API documentation Link to the API
* Three example API calls related to the core functionality of your application. You must provide all details needed to perform the calls (i.e., required parameter values). In other words, these calls must be replicable. You may include Postman collections.

**Comment by bakikucukcakiroglu** [comment]
[API Documentation](https://documenter.getpostman.com/view/30817138/2s9YRGy9fA)

**Comment by bakikucukcakiroglu** [comment]
Done! Can be checked in Final Milestone Report!

<img width="739" alt="Screenshot 2023-12-29 at 19 13 05" src="https://github.com/bounswe/bounswe2023group8/assets/61244299/74e7fb94-e973-45ee-8b1f-735163064440">
