### ISSUE TITLE
Add Class Diagrams to Wiki Page

### ISSUE THREAD

**Issue by bakikucukcakiroglu** [bounswe/bounswe2023group8#63]
- Class Diagrams should be added to Wiki Page.

- Sidebar nav should be arranged accordingly.

- An out-link should be given to original source.

**Comment by orkunkilic** [comment]
Created.

TO-DO:

- [ ] Add Class Diagrams to page
- [ ] Add original resource
- [ ] Nav-link

**Comment by orkunkilic** [comment]
Completed.
