### ISSUE TITLE
Milestone 1 Group Report  DEADLINE: 10 APRIL 

### ISSUE THREAD

**Issue by bakikucukcakiroglu** [bounswe/bounswe2023group8#64]
Milestone report must include the following items:

- A section for self-introduction with the course name, group number, and contributors.

- Table of Contents

- Executive Summary: Summary of project status and any changes in plans based on reflections.

- List and status of deliverables.

- Evaluation of the status of deliverables and its impact on your project plan.

- Evaluation of tools and processes that you have used to manage your team project.

- Individual Contribution Reports. (a list of member contributions in alphabetic order by member SURNAME. See description of individual reports below).

**Comment by EgemenKaplan** [comment]
[Issue](https://github.com/bounswe/bounswe2023group8/issues/65) of self-introduction section

**Comment by bakikucukcakiroglu** [comment]
This was the main issue for Milestone 1 Report. It can closed since all related issues are done.
