### ISSUE TITLE
Project - System Manual

### ISSUE THREAD

**Issue by celikomerfaruk** [bounswe/bounswe2023group8#649]
- System requirements and installation instructions for the mobile application. Mobile application also provide instructions for use with an emulator. 

- System requirements and installation instructions for the web application.

- Must include docker installation instructions.

**Comment by bakikucukcakiroglu** [comment]
[Go to docker installation instructions.](https://github.com/bounswe/bounswe2023group8/releases/tag/final-submission-g8)

**Comment by bakikucukcakiroglu** [comment]
Docker installation instruction added to Final Milestone Report!

**Comment by celikomerfaruk** [comment]
Finished the mobile app guide. You can check [here](https://github.com/bounswe/bounswe2023group8/blob/main/app/mobile/README.md). Also added to the Final Milestone Report.
