### ISSUE TITLE
Milestone Report - Introduction

### ISSUE THREAD

**Issue by EgemenKaplan** [bounswe/bounswe2023group8#65]
A section for self-introduction with the course name, group number, and contributors.
(Optional) It might be nice to write contributor names with their "About me" pages as hyperlinks.

**Comment by bakikucukcakiroglu** [comment]
Task that are done:

- Created a shared milestone report file

- Created a cover page for the report

- Added members and embedded wiki about me page links of the members to report

- Created table of contents 



<img width="317" alt="Screen Shot 2023-04-09 at 13 02 45" src="https://user-images.githubusercontent.com/61244299/230766580-4a5197f0-b672-4fd4-9ebe-48b02519b475.png">

<img width="322" alt="Screen Shot 2023-04-09 at 13 03 29" src="https://user-images.githubusercontent.com/61244299/230766609-769a6cd2-cb66-495d-b522-a3efa61d0f55.png">
