### ISSUE TITLE
Use Case Diagram Revision

### ISSUE THREAD

**Issue by MericKeskin** [bounswe/bounswe2023group8#67]
Use case diagram had some properties unattached. Also some rearrangement is needed.

**Comment by MericKeskin** [comment]
- Connected Moderator to User and added a case to make Moderator available to moderate on Interest Areas.
- Rearranged diagram slightly for clarity.

**Comment by bakikucukcakiroglu** [comment]
I arranged the style of diagram to make it more attractive to help Meriç.

**Comment by MericKeskin** [comment]
- Connected Admin to User.
- Completen use cases.
