### ISSUE TITLE
Milestone Report - Evaluation of Deliverables - Project Repository

### ISSUE THREAD

**Issue by sudek0** [bounswe/bounswe2023group8#74]
TODOS:
- Add an evaluation text for our repository.

**Comment by bakikucukcakiroglu** [comment]
Done. Can be seen by the following image:

<img width="687" alt="Screen Shot 2023-04-09 at 15 00 35" src="https://user-images.githubusercontent.com/61244299/230771278-4551edbb-39e5-44bc-9ebd-3e765f65b52c.png">
