### ISSUE TITLE
Milestone Report - Evaluation of Deliverables - Software Requirement Specification

### ISSUE THREAD

**Issue by sudek0** [bounswe/bounswe2023group8#75]
TODOS: 
- Add an evaluation text for Requirement Analysis of the project.
- Evaluate each section (Functional, Non-Functional, User, System)

**Comment by EgemenKaplan** [comment]
I evaluated our Software Requirements Specification,  its elicitation process, described this process in our Milestone 1 Report.

The evaluation can be found [here](https://github.com/bounswe/bounswe2023group8/wiki/Milestone-1-Report#32-software-requirement-specification)
