### ISSUE TITLE
Milestone Report - Evaluation of the Deliverables - Software design documents in UML: Use Case

### ISSUE THREAD

**Issue by sudek0** [bounswe/bounswe2023group8#77]
TODOS: 
- Add an evaluation text for Use Cases of the project.

**Comment by MericKeskin** [comment]
Use cases are completed and ready for implementation.

**Comment by sudek0** [comment]
Added evaluation text and the image of the use case diagrams.
Work done can be seen [here](https://github.com/bounswe/bounswe2023group8/wiki/Milestone-1-Report).
