### ISSUE TITLE
Milestone Report - Milestone Report

### ISSUE THREAD

**Issue by ozturkMirac** [bounswe/bounswe2023group8#84]
TODOs:

- Edit and review  the milestone report.

**Comment by bakikucukcakiroglu** [comment]
Done, can be checked [here](https://github.com/bounswe/bounswe2023group8/wiki/Milestone-1-Report).

Also can be seen by the following image:

<img width="926" alt="Screen Shot 2023-04-10 at 23 11 42" src="https://user-images.githubusercontent.com/61244299/230989131-22d1bbea-77c0-4cae-9bb9-30f4ba95feb3.png">
