### ISSUE TITLE
Add Project Requirements to Milestone 1 Report Page

### ISSUE THREAD

**Issue by begumyivli** [bounswe/bounswe2023group8#86]
Milestone 1 report page has already been created. There is a "Software Requirement Specification" section. Take the project requirements from "Requirements" page and add them to corresponding section.

**Comment by bakikucukcakiroglu** [comment]
Done. Can be checked  [here](https://github.com/bounswe/bounswe2023group8/wiki/Milestone-1-Report). 

A preview can be seen by the following image:

<img width="949" alt="Screen Shot 2023-04-09 at 15 14 41" src="https://user-images.githubusercontent.com/61244299/230771916-8359fb58-dd2c-4e5e-b969-c23331ac2ad8.png">
