### ISSUE TITLE
Add Mockups to Wiki

### ISSUE THREAD

**Issue by begumyivli** [bounswe/bounswe2023group8#88]
Instead of Mockup drafts, each mockup design in figma will be appended to mockups page on wiki

**Comment by MericKeskin** [comment]
- Web mock-ups are ready to be added to wiki.

**Comment by MericKeskin** [comment]
- Upgraded web mock-ups slightly, if already appended to wiki it is a choice to reappend.
- Mobile mock-ups are ready to be appended to wiki.

**Comment by begumyivli** [comment]
- web mockups added to wiki
- mobile mockups added to wiki
